[package]
name = "nitro-enclave-attestation-verifier"
version = "0.1.0"
authors = ["asa93"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_cbor = { version = "0.11.2", default-features = true, features = [
    "alloc",
] }
base64 = "0.22.1"
x509-cert = { version = "0.2.5", default-features = false }
rsa = "0.8.0"
#pem = "3.0.1"
p384 = { version = "0.13.0", default-features = false, features = [
    "arithmetic",
    "ecdh",
    "ecdsa",
    "test-vectors",
    "expose-field",
    "pkcs8",
    "sha384",
] }
